Revert "vfs: make sure struct filename->iname is word-aligned"
breaks kernel compilation
fs/namei.o: In function `getname_flags':
namei.c:(.text+0x2c): undefined reference to `__compiletime_assert_134'
make[2]: *** No rule to make target 'vmlinux', needed by 'arch/arm64/boot/Image'.  Stop.
make[1]: *** [arch/arm64/Makefile:220: Image] Error 2

This reverts commit e1d30c14d6f7d7acf61289607204c6e533ac436c.

Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>